using Game.Controllers.Controls;
using Game.Controllers.Initialize;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by InstallerGenerator based on Entitas.InstallerGenerator2 by SmokyOoOwizard.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game
{
	public class ControllersInstaller : MonoInstaller
    {
		public override void InstallBindings()
        {
            var container = Container;
			Urgent(container);
			Normal(container);
            Container.BindInterfacesAndSelfTo<Bootstrap.Bootstrap>().AsSingle().NonLazy();
		}

		private void Urgent(DiContainer container)
		{
			// 0001
			container.BindInterfacesAndSelfTo<InitializeController>().AsSingle();	// 0001
		}

		private void Normal(DiContainer container)
		{
			// 0045
			container.BindInterfacesAndSelfTo<AimingController>().AsSingle();	// 0045
			container.BindInterfacesAndSelfTo<MovementController>().AsSingle();	// 0050
			container.BindInterfacesAndSelfTo<AttackController>().AsSingle();	// 0055

			// 0070
			container.BindInterfacesAndSelfTo<ReloadingController>().AsSingle();	// 0070

			// 0100
			container.BindInterfacesAndSelfTo<EnemySpawnController>().AsSingle();	// 0100
		}	
    }
}